### ISSUE TITLE
Facturation de CEA CADARACH

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/Facturation#9]
Catherine BALLEREAU : 

> Nous devons établir une facture à CEA CADARACHE ID 16192 pour le mois d’avril, le montant est à zéro au lieu de 352.45HT

**Comment by MamboJoel** [comment]
Sur [cette page](http://comptabilite.sdpv.com/Ugap/ClientUgap.aspx?ID=16192) on devrait avoir 352.45HT et on a 0.

**Comment by MamboJoel** [comment]
J'ai trouvé. Ces véhicules étaient entrés en gestion le 3 avril au lieu du premier. Je les ai passé au premier.

**Comment by PIEGAY** [comment]
La date de début de gestion est bien le 3/04.
Je dois facturé 27/30ème du mois pour le mois d'avril (le 1er mois de facturation est toujours au prorata).

**Comment by PIEGAY** [comment]
C'est bon dans Fleet j'ai bien les 27/30ème d'un mois pour le mois d'avril et 1 mois complet pour mai

Super !

**Comment by MamboJoel** [comment]
Je ne me l'explique pas. Car j'ai mis les dates d'entrée au 1er avril, et ça n'est pas une blague.
Mais bon, si le problème est résolu...
